######################################################################
# Pool
# - Volumen: 45 m³
# - Salzwasserpool, Salzkonzentration Zodiac LM2: 3200–4000 ppm
# - Temperatur Referenz: 25 °C
# - Idealer pH-Wert: 7.2

# Poolpumpe
# - Förderleistung bei 100%: 12 m³/h
# - Frequenz über Inverter steuerbar

# Chlorinator / Elektrolyse
# - Zodiac LM2-40, max 40 g/h Chlor
# - ORP Zielwert: 750 mV
# - Chlorbedarf wird über ORP Δ ermittelt

# PH-Dispenser
# - Maximal pro Zyklus: 100 ml
# - Maximal pro Tag: 300 ml
# - Tankkapazität: 20 L
######################################################################

substitutions:
  device_name: "poolcontroller"
  friendly_name: "pool"

  #wifi domain to use, standard =  .local
  domain: .local
  #domain: !secret domain_iot
  #domain: !secret domain_pidri

  ssid1_ap: !secret wifi_pidri
  ssid1_pw: !secret wifi_pidri_pass
  ssid2_ap: !secret wifi_autox
  ssid2_pw: !secret wifi_autox_pass

  #GPIO definitions
  pin_relay1:               GPIO25
  pin_relay2:               GPIO26
  pin_relay3:               GPIO33
  pin_relay4:               GPIO32
  ledwifi:                  GPIO04
  buzzer:                   GPIO12
  txd0:                     GPIO01 #UART Tuya Reader (not needed actually)
  rxd0:                     GPIO03 #UART Tuya Reader
  txd1:                     GPIO17 #UART Modbus RS485
  rxd1:                     GPIO16 #UART Modbus RS485
  pwmh_hbridge:             GPIO13 #s2cs - brought outside to screw header as I/O
  spics0:                   GPIO05
  spiclk:                   GPIO18
  spimiso:                  GPIO19
  spimosi:                  GPIO23
  i2csda:                   GPIO21
  i2cscl:                   GPIO22
  i2cint:                   GPIO02
  prog:                     GPIO00 #Für Flash auf GND ziehen, EN kurz auf GND ziehen danach wieder loslassen (3,3V)

  #Input_only GPIOs - All Screw Header
  yfdn40:                   GPIO34
  yfs201:                   GPIO35
  phtank_reset:             GPIO36
  maintenance:              GPIO39

  #Input/Output GPIO - All Screw Header
  phase_hbridge:            GPIO14
  onewire:                  GPIO15
  inout16:                  GPIO16
  inout27          :        GPIO27 #GPIO27 / RF433

  #Code Subs
  modbusid_freq_inv:      modbus_freq_inv
  modbusid_heat_pump:     modbus_sunway
  modbusid_energy_meter:  meter_ds100
  name_pzem17:            Elektrolyse

################Die goldene Regel der Prioritäten###############################
################################################################################
# In ESPHome gilt: Höhere Zahlen werden zuerst ausgeführt.
# 800.0 (WLAN/Netzwerk)
# 600.0 (Core)
# 200.0 (Standard Sensoren)
# 40.0 (UART Bus Default) Die Hardware-Schnittstelle muss bereit sein.
# 40.0 (Modbus Hub Default) Der Controller, der die Kommunikation verwaltet und zeitgleich mit UART startet
# 40.0 (Modbus Sensor Default) Erbt die Priorität des Controllers.
# -15.0 (Dein Ziel für on_boot)

# Für den Poolcontroller folgendes:
# 800.0 (WLAN/Netzwerk)
# 600.0 (Core)
# 200.0 (Standard Sensoren)
# 40.0 (UART Bus) Die Hardware-Schnittstelle muss bereit sein.
# 35.0 (Modbus Hub) Der Controller, der die Kommunikation verwaltet und zeitgleich mit UART startet
# 30.0 (Modbus Sensor) Erbt die Priorität des Controllers.
# 10.0 (Dein Ziel für on_boot)

# Zentrale Verwaltung der Prioritäten
  uart_prior:       "40.0"
  modbushub_prior:  "35.0"
  modbusctrl_prior: "30.0"
  on_boot_prior:    "10.0"

  #Update frequency und command throttle für Modbus
      #command_throttle (Optional, Time): minimum time in between 2 requests to the device. Default is 0ms.
      #update_interval (Optional, Time): The interval that the sensors should be checked. Defaults to 60 seconds.
  throttle_modbus_heatpump:      "200ms"
  upd_int_modbus_heatpump:       "60s"
  throttle_modbus_energy_meter:  "5s"
  upd_int_modbus_energy_meter:   "60s"

  # #Poolcontroller-Logics Intial Values
  checkIntervalORP: "2 min" #Angabe nach der Zahl ist wichtig!!
  checkIntervalPH: "15 min" #Angabe nach der Zahl ist wichtig!!

esphome:
  name: "${friendly_name}"
  project:
    name: "autox86.poolparty"
    version: "1.0.1"
  on_boot:
    priority: ${on_boot_prior}
    then:
      - script.execute: script_on_boot

packages:
  globals: !include packages/globals.yaml
  buttons: !include packages/buttons.yaml
  dynamic_on_time: !include packages/dynamic_on_time.yaml
  intervals: !include packages/intervals.yaml
  numbers: !include packages/numbers.yaml
  scripts: !include packages/scripts.yaml
  selects: !include packages/selects.yaml
  sensors: !include packages/sensors.yaml
  switches: !include packages/switches.yaml
  text_sensors: !include packages/text_sensors.yaml
external_components:
  - source: github://hostcc/esphome-component-dynamic-on-time

esp32:
  board: esp-wrover-kit
  framework:
    #type: arduino
    type: esp-idf



status_led:
#LED-Zustand Bedeutung
# Blinken langsam ->  WLAN wird gesucht
# Blinken schnell ->  Verbindung zu API/MQTT noch nicht fertig
# Dauerlicht AN ->  WLAN + API/MQTT OK
# Aus -> Gerät ist aus / GPIO invertiert
  pin:
    number: ${ledwifi}
    inverted: true

output:
  - platform: ledc
    pin: ${buzzer}
    id: rtttl_out

rtttl:
  output: rtttl_out

#Must be activated to enter safe mode after 10 failed normal boot
safe_mode:

# https://esphome.io/components/esphome.html#adjusting-flash-writes
preferences:
  #setting interval to 5 minutes since this defines writing to flash
  #Created a specific save script that is executed for things that need
  #to save more quickly.
  flash_write_interval: 5min

#Enable logging
debug:
  update_interval: 5s

#Logger must be at least debug (default)
logger:
  level: DEBUG
  #level: INFO
  baud_rate: 0
  #enable for serial debugging
  #baud_rate: 115200

#Enable Home Assistant API
api:
  encryption: 
    key: !secret api_key
  #no reboot in case HA is down - can require full reboot when HA is back
  reboot_timeout: 0s
  on_client_connected:
    then:
      - delay: 2s  # Kurze Gedenksekunde, bis der Log-Stream stabil ist
      - lambda: |-
          if (!id(boot_log_buffer).empty()) {
            ESP_LOGW("boot_report", "---------------------------------------");
            ESP_LOGW("boot_report", "   ZUSAMMENFASSUNG DES BOOT-VORGANGS   ");
            ESP_LOGW("boot_report", "---------------------------------------");
            
            // Gibt den gesamten gesammelten Textblock aus
            ESP_LOGW("boot_report", "%s", id(boot_log_buffer).c_str());
            
            ESP_LOGW("boot_report", "---------------------------------------");

            // Optional: Wenn du den Bericht NUR EINMAL sehen willst (pro Reboot):
            //id(boot_log_buffer) = ""; 
          }

ota:
  platform: esphome
  password: !secret ota_pass

wifi:
  #https://esphome.io/components/wifi.html#power-save-mode
  power_save_mode: none
  #No reboot if Wifi is missing - can require full reboot when wifi is back
  reboot_timeout: 0s
  domain: "${domain}"

  networks:
    - ssid: "${ssid1_ap}"
      password: "${ssid1_pw}"
    - ssid: "${ssid2_ap}"
      password: "${ssid2_pw}"
    
    #https://esphome.io/components/wifi.html#connecting-to-multiple-networks
    #Instead using a AP, using a Rescue Network, so you can span a AP 
    #with your mobile and ESP is connecting to the same
    - ssid: "rescue"
      password: "safemysoul"

  on_connect:
    then:
      - lambda: |-
          ESP_LOGI("wifi", "Verbunden mit SSID: %s, IP: %s",
                  id(wifi_sta_ssid).state.c_str(),
                  id(wifi_sta_ip).state.c_str());

  on_disconnect:
    then:
      - lambda: |-
          ESP_LOGW("wifi", "WLAN getrennt");

  ap:

#Enable Web server
web_server:
  port: 80
  version: 3
  #Load JScript locally, so no internet required
  css_include: "pool_webserver.css"
  # Falls du auch JavaScript lokal haben willst (kein Internet für UI nötig):
  local: true
  sorting_groups:
    - id: grp_status
      name: "Status"
      sorting_weight: 40
    - id: grp_sensors
      name: "Sensoren"
      sorting_weight: 60
    - id: grp_timer
      name: "Timer"
      sorting_weight: 80
    - id: grp_error
      name: "Fehler/Status"
      sorting_weight: 90
    - id: grp_config
      name: "Konfiguration"
      sorting_weight: 100
    - id: grp_system
      name: "System"
      sorting_weight: 120
    - id: grp_debug
      name: "Diagnostik + Testing only (Gefährlich kaum Sicherheiten!)"
      sorting_weight: 140

captive_portal:

#Sync time with SNTP
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
    - pool.ntp.org
    on_time:
      - seconds: 2
        minutes: 0
        hours: 0
        then:
          - logger.log: 
              format: "Zähler für tägliche Mengen zurückgesetzt."
              level: info
          - lambda: |
              id(ph_today_ml) = 0.0;
              id(ph_last_cycle_ml) = 0.0;
              id(phdispenser_cycle_time) = 0.0;
              id(phdispenser_today_run_time) = 0.0;
              id(ph_cycles) = 1.0;
              id(ph_max_injection_reached) = false;
              id(chlorinator_today_run_time) = 0.0;
              id(chlorinator_max_reached) = false;
              id(chlorinator_remaining_seconds) = 0;
              id(chlor_needed) = false;
              id(ph_needed) = false;

uart:
#Tuya RX / TX
  - id: uart_0
    tx_pin: ${txd0}
    rx_pin: ${rxd0}
    baud_rate: 115200
    rx_buffer_size: 512
    setup_priority: ${uart_prior}
  

#Modbus for Rocket Controller (8N1)
  - id: modbus_uart
    tx_pin: ${txd1}
    rx_pin: ${rxd1}
    baud_rate: 9600
    stop_bits: 1
    parity: NONE
    setup_priority: ${uart_prior}

one_wire:
  - platform: gpio
    pin: 
      number: ${onewire}

modbus:
  uart_id: modbus_uart
  id: rocket_modbus
  setup_priority: ${modbushub_prior}

modbus_controller:
- id: modbus_freq_inv
  modbus_id: rocket_modbus
  address: 0x05
  setup_priority: ${modbushub_prior}
  command_throttle: 200ms
  update_interval: 5s
  max_cmd_retries: 1 #Default:4, nach zwei Fehlversuchen wird das Gerät als Offline markiert
  on_offline:
    then:
      - lambda: |-
          ESP_LOGW("modbus_freq_inv", "Controller meldet: Gerät ist offline. Nulle Sensoren.");
          id(bs_inv_online).publish_state(false);
          id(inv_voltage_out).publish_state(0.00);
          id(inv_voltage_bus).publish_state(0.00);
          id(inv_current_out).publish_state(0.00);
          id(inv_torque_out).publish_state(0.00);
          id(inv_speed).publish_state(0.00);
          id(inv_running).publish_state(NAN);
  on_online:
    then:
      - binary_sensor.template.publish:
          id: bs_inv_online
          state: ON

- id: ${modbusid_heat_pump}
  modbus_id: rocket_modbus
  address: 0x01
  setup_priority: -10
  command_throttle: ${throttle_modbus_heatpump}
  update_interval: ${upd_int_modbus_heatpump}
  on_offline:
    then:
      - lambda: |-
          ESP_LOGW("${modbusid_heat_pump}", "Controller meldet: Gerät ist offline. Nulle Sensoren.");
          id(bs_hp_online).publish_state(false);
  on_online:
    then:
      - binary_sensor.template.publish:
          id: bs_hp_online
          state: ON

- id: ${modbusid_energy_meter}
  modbus_id: rocket_modbus
  address: 0x04
  setup_priority: -10
  command_throttle: ${throttle_modbus_energy_meter}
  update_interval: ${upd_int_modbus_energy_meter}
  on_offline:
    then:
      - lambda: |-
          ESP_LOGW("${modbusid_energy_meter}", "Controller meldet: Gerät ist offline. Nulle Sensoren.");
          id(bs_energy_meter_online).publish_state(false);
  on_online:
    then:
      - binary_sensor.template.publish:
          id: bs_energy_meter_online
          state: ON

- id: pzem_hub
  modbus_id: rocket_modbus
  address: 0x01
  setup_priority: -10
  command_throttle: 100ms
  #Das update interval wird nun auf Sensorebene vergeben
  update_interval: "4s"
  max_cmd_retries: 1 #Default:4, nach zwei Fehlversuchen wird das Gerät als Offline markiert
  on_offline:
      then:
        - lambda: |-
            ESP_LOGW("pzem_hub", "Controller meldet: Gerät ist offline. Nulle Sensoren.");
            id(bs_pzem_online).publish_state(false);
            id(pzem_dc_voltage).publish_state(0.0);
            id(pzem_dc_current).publish_state(0.0);
            id(pzem_dc_power).publish_state(0.0);
  on_online:
    then:
      - binary_sensor.template.publish:
          id: bs_pzem_online
          state: ON

#Tuya with ignoring what we do not need
tuya:
  uart_id: uart_0
  ignore_mcu_update_on_datapoints: 
  - "102"
  - "103"
  - "107"
  - "108"
  - "143"
  - "142"
  - "141"
  - "138"
  - "137"
  - "136"
  - "128"
  - "127"
  - "126"
  - "123"
  - "122"
  - "121"
  - "118"
  - "117"
  - "116"
  - "113"
  - "112"
  - "111"
  - "132"
  - "133"